language: python
python:
- 3.8
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: <api_deploy_key>
  app: spotifyalert-chatbot
sh$ cd /path/to/your/project
sh$ gem install travis
sh$ heroku login
Email: siriwarin22@gmail.com
Password: 0896519537z
Logged in as youremail@domain.com
sh$ travis encrypt $(heroku auth:token) --add deploy.api_key
